---

galaxy_info:
  author: Mats Blomdahl
  description: Docker host provisioning.

  license: MIT

  min_ansible_version: 2.5

  platforms:
    - name: EL
      versions:
        - 7
        - 8

  galaxy_tags:
    - docker

dependencies: []

...
